services:
  app:
    container_name: zetachain-cctx-app
    image: zetachain-cctx-server:latest
    platform: linux/amd64
    ports:
      - "8050:8050"
    environment:
      - ZETACHAIN_CCTX__CONFIG=config/testnet.toml
    depends_on:
      - database
    volumes:
      - ./config:/app/config
    networks:
      - caddy_net

  database:
    container_name: zetachain-cctx-database
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=zetachain_cctx
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - caddy_net

  caddy:
    image: caddy:2
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - caddy_net

volumes:
  caddy_data:
  caddy_config:
  postgres_data:

networks:
  caddy_net:
    driver: bridge  