//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "cross_chain_tx")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub creator: String,
    #[sea_orm(unique)]
    pub index: String,
    pub zeta_fees: String,
    pub lock: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub relayed_message: Option<String>,
    pub last_status_update_timestamp: DateTime,
    pub protocol_contract_version: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::cctx_status::Entity")]
    CctxStatus,
    #[sea_orm(has_many = "super::inbound_params::Entity")]
    InboundParams,
    #[sea_orm(has_many = "super::outbound_params::Entity")]
    OutboundParams,
    #[sea_orm(has_many = "super::revert_options::Entity")]
    RevertOptions,
}

impl Related<super::cctx_status::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CctxStatus.def()
    }
}

impl Related<super::inbound_params::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InboundParams.def()
    }
}

impl Related<super::outbound_params::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OutboundParams.def()
    }
}

impl Related<super::revert_options::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RevertOptions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
